#pragma once

/*
 * Enumeration of possible errors when parsing ASM.
 */
enum asm_parse_error {
	ASM_PARSE_ERROR_NO_ERROR,
	ASM_PARSE_ERROR_NO_DECLARATION,

	ASM_PARSE_ERROR_UNEXPECTED_EOF,
	ASM_PARSE_ERROR_EXTRA_INPUT,

	ASM_PARSE_ERROR_INVALID_SYMBOL_START,

	ASM_PARSE_ERROR_A_INSTRUCTION_MISSING_AT_SYMBOL,
	ASM_PARSE_ERROR_A_INSTRUCTION_ADDRESS_TOO_LARGE,

	ASM_PARSE_ERROR_C_MALFORMED,
	ASM_PARSE_ERROR_C_DEST_MALFORMED,
	ASM_PARSE_ERROR_C_A_COMP_MALFORMED,
	ASM_PARSE_ERROR_C_JUMP_MALFORMED,
};

// TODO: Function to pretty print each type of asm_parse_error
